sudo: false
dist: bionic
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-9
compiler:
  - gcc
env:
   - CC=gcc9 
   - CXX=g++9
script:
  - cmake .
  - cmake --build .
#  - ctest --verbose