sudo: false
dist: bionic
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-9
    - cmake
compiler:
  - gcc
env:
   - CC=gcc-9 CXX=g++-9
script:
  - cmake .
  - cmake --build .
#  - ctest --verbose

notifications:
  email: false